cmake_minimum_required(VERSION 3.19.0)

set(CMAKE_POSITION_INDEPENDENT_CODE ON)

include_directories(
    ${CMAKE_CURRENT_SOURCE_DIR}/src
)

aux_source_directory(${CMAKE_CURRENT_SOURCE_DIR}/src PROJECTLIBSRC)

add_library(${PROJECTLIB} STATIC ${PROJECTLIBSRC})

file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/src/Example.h
     DESTINATION ${CMAKE_INCLUDE_OUTPUT_DIRECTORY})

set(CMAKE_POSITION_INDEPENDENT_CODE OFF)